### ISSUE TITLE
Cronjobs einrichten

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/muenster-info-hub#32]
Die Scraper sollten regelmäßig laufen.

**Comment by tomsrocket** [comment]
Also zwei Importer habe ich zunächst auf meinem Server eingerichtet: 
- meinestadt
- münster-top-events

**Comment by JonesH** [comment]
Die scrapy Importer koennte ich auf einem meiner Server laufen lassen.

**Comment by tomsrocket** [comment]
Hab ich jezt erstmal auch bei mir eingerichet, dann ist alles am gleichen Ort.
