### ISSUE TITLE
Scraper-Dashboard erstellen

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/muenster-info-hub#33]
Eine Übersicht mit ein paar Kennzahlen für die verschiedenen Termin-Quellen bauen (dafür gibts ja ein eigenes Feld im Elasticsearch).
Wir sollten sehen können:
=> wieviele in der Zukunft liegende termine haben wir von welcher Quelle
Daran kann man dann sehen ob ein scraper kaputt ist, oder nicht läuft, nämlich wenn davon keine Termine mehr reinkommen.

Vielleicht wäre für jede Quelle auch interessant: 
- wieviele events haben bilder
- wieviele events haben geokoordinaten
etc...? weitere?

Soweit ich das sehe, könnte man das sogar als statisches html bauen, nur mit ein bissel Javascript für die elasticsearch-Abfrage.

**Comment by nichoio** [comment]
Benutzt man für sowas nicht Airflow? Bin kein Experte

**Comment by tomsrocket** [comment]
Beta Version ist live unter: http://stats.muenster.jetzt

**Comment by ubergesundheit** [comment]
BÃ¶ses Encoding

**Comment by tomsrocket** [comment]
Ecoding gefixt.
