### ISSUE TITLE
Scraper für Münster events

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/muenster-info-hub#36]
Nach dem Vorbild vom Repository "ms-event-scrapy" sollten wir auch die Events der Stadt Münster importieren.

**Comment by JonesH** [comment]
Koennen wir nicht einfach den bestehenden scraper nutzen?

**Comment by JonesH** [comment]
Hab eine modifizierte Variante von EventSpider.py hinzugefuegt (#47)
